[package]
name = "llama-lsp"
version = "0.1.0"
edition = "2021"

[dependencies]
llm-daemon = { version = "0.5.6", features = ["cuda"] }
lsp-server = "0.7.8"
lsp-types = "0.97.0"
serde = "1.0.217"
serde_json = "1.0.137"
